name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest --alluredir=reports/
    - name: Upload Allure report
      uses: allure-framework/allure-action@v1.0.0  # Usa esta versión estable
      with:
        allure-results: reports/
    - name: Debug Information
      run: |
        echo "Printing debug information"
        ls -la  # Muestra el contenido del directorio
